openapi: 3.0.0
info:
  title: My Application API
  description: API for interacting with various functionalities of My Application, including document management and other features.
  version: 1.0.0
servers:
  - url: https://rhetorically-98ba2.web.app
    description: Main Application API server
paths:
  /api/listDocs:
    get:
      operationId: listDocs
      summary: List document title from Google Drive
      description: Retrieves a list of document titles from Google Drive. Requires OAuth 2.0 authentication.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: An array of Google Drive document titles and ids.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier of the Google Drive document.
                    title:
                      type: string
                      description: The title of the Google Drive document.
        "401":
          description: Unauthorized - User not logged in or invalid/expired token.
        "405":
          description: Method Not Allowed

  /api/getIndexedText:
    get:
      operationId: getIndexedText
      summary: Returns text of a Google Doc with index annotated given id.
      description: Returns the text of a Google Doc given the documentId. Parts of the text has index annotated. Indexes throughout the text are denoted within <$> tags (the number delimited in the tag is the index). Requires OAuth 2.0 authentication.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: documentId
          required: true
          description: The ID of the Google Document.
          schema:
            type: string
      responses:
        "200":
          description: Successful response with document text.
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Returns a confirmation with the url of the edited document
        "400":
          description: Missing query - documentId.
        "401":
          description: Unauthorized - User not logged in or invalid/expired token.
        "405":
          description: Method Not Allowed
  /api/highlightText:
    post:
      operationId: highlightText
      summary: Highlights specified text ranges in a Google Doc.
      description: Highlights sections of a Google Doc based on provided text ranges. Requires OAuth 2.0 authentication.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: documentId
          required: true
          description: The ID of the Google Document.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sections:
                  type: array
                  items:
                    type: object
                    properties:
                      startIndex:
                        type: integer
                        format: int32
                      endIndex:
                        type: integer
                        format: int32
      responses:
        "200":
          description: Successfully highlighted text.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Returns a confirmation with the url of the edited document
        "400":
          description: Missing query - documentId.
        "401":
          description: Unauthorized - User not logged in or invalid/expired token.
        "405":
          description: Method Not Allowed
